name: Publish Release Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Build
        run: ./gradlew build -Pgithub_sha=${{ github.sha }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libs/*.jar
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
